/* ─────────────────────────────────────────────────────────────────────────────
   portal-config.js  —  Staff roster & directory
───────────────────────────────────────────────────────────────────────────── */
var PORTAL_CONFIG = {

  // ── Company News & Announcements ──────────────────────────────────────────
  // category options: 'General' | 'HR' | 'Operations' | 'Leadership' | 'Safety'
  // pinned: true keeps the item at the top regardless of date order
  news: [
    {
      date:     '2026-09-15',
      category: 'General',
      title:    'Employee Portal Now Live',
      body:     'Your new self-service portal is live. Access pay information, submit incident reports, review the Employee Handbook, and more — all from one place.',
      pinned:   true,
    },
  ],

  // ── Company Directory (A–Z by first name) ─────────────────────────────────
  // country: 'US' | 'India' | 'Pakistan'
  directory: [
    { name: 'Abdul Fateh',               email: 'afateh@americloudtelecom.com',           country: 'US'       },
    { name: 'Abelino Bautista',          email: 'abautista@americloudtelecom.com',         country: 'US'       },
    { name: 'Abhay Sharma',              email: 'asharma@americloudtelecom.com',           country: 'India'    },
    { name: 'Afzal Karim',               email: 'akarim@americloudtelecom.com',            country: 'US'       },
    { name: 'Ahmed Ghani',               email: 'aghani@americloudtelecom.com',            country: 'US'       },
    { name: 'Ahmed Syed',                email: 'ahsyed@americloudtelecom.com',            country: 'US'       },
    { name: 'Ajay Kumar Andapally',      email: 'ajkumar@americloudtelecom.com',           country: 'US'       },
    { name: 'Akshay Gupta',              email: 'agupta@americloudtelecom.com',            country: 'India'    },
    { name: 'Alexis Pena',               email: 'apena@americloudtelecom.com',             country: 'US'       },
    { name: 'Ali Ahmed Zaidi Syed',      email: 'szaidi@americloudtelecom.com',            country: 'US'       },
    { name: 'Amaechi Nwankwo',           email: 'anwankwo@americloudtelecom.com',          country: 'US'       },
    { name: 'Amarjeet Singh Rathore',    email: 'arathaur@americloudtelecom.com',          country: 'India'    },
    { name: 'Ammar Khan',                email: 'akhan@americloudtelecom.com',             country: 'US'       },
    { name: 'Anand Tiwari',              email: 'atiwari@americloudtelecom.com',           country: 'India'    },
    { name: 'Anmol Ahsan',               email: 'aahsan@americloudtelecom.com',            country: 'Pakistan' },
    { name: 'Apurv Nayan',               email: 'anayan@americloudtelecom.com',            country: 'India'    },
    { name: 'Arnell Avecilla',           email: 'aavecilla@americloudtelecom.com',         country: 'US'       },
    { name: 'Arslan Arif',               email: 'marslan@americloudtelecom.com',           country: 'Pakistan' },
    { name: 'Arvin Mariano Fernandez',   email: 'amariano@americloudtelecom.com',          country: 'US'       },
    { name: 'Asim Mallick',              email: 'amallick@americloudtelecom.com',          country: 'India'    },
    { name: 'Ayesha Fouad',              email: 'afouad@americloudtelecom.com',            country: 'Pakistan' },
    { name: 'Ayesha Syed',               email: 'accounts@americloudtelecom.com',          country: 'US'       },
    { name: 'Bakhtawar Jabeen',          email: 'bjabeen@americloudtelecom.com',           country: 'Pakistan' },
    { name: 'Boopathi Shanmugasundaram', email: 'sboopathi@americloudtelecom.com',         country: 'India'    },
    { name: 'Chandra Mohan Pal',         email: 'cmpal@americloudtelecom.com',             country: 'India'    },
    { name: 'Chintan Kumar Patel',       email: 'cpatel@americloudtelecom.com',            country: 'US'       },
    { name: 'Daniel Lapada',             email: 'dlapada@americloudtelecom.com',           country: 'US'       },
    { name: 'Dharmendra Prasad',         email: 'dprasad@americloudtelecom.com',           country: 'India'    },
    { name: 'Dinesh Pottunuri',          email: 'dpottunuri@americloudtelecom.com',        country: 'US'       },
    { name: 'Esteban Fernandez',         email: 'efernandez@americloudtelecom.com',        country: 'US'       },
    { name: 'Fahad Ghulam',              email: 'fghulam@americloudtelecom.com',           country: 'Pakistan' },
    { name: 'Ferdinand Nicasio',         email: 'fnicasio@americloudtelecom.com',          country: 'US'       },
    { name: 'Gary Polloso',              email: 'gpolloso@americloudtelecom.com',          country: 'US'       },
    { name: 'Gokul Adusumalli',          email: 'gadusumalli@americloudtelecom.com',       country: 'India'    },
    { name: 'Hajira Bibi',               email: 'hbibi@americloudtelecom.com',             country: 'Pakistan' },
    { name: 'Hamza Shahzad',             email: 'hshahzad@americloudtelecom.com',          country: 'Pakistan' },
    { name: 'Hirdesh Sharma',            email: 'hsharma@americloudtelecom.com',           country: 'India'    },
    { name: 'Humzah Shoaib',             email: 'hshoaib@americloudtelecom.com',           country: 'US'       },
    { name: 'Isaiah Nicasio',            email: 'inicasio@americloudtelecom.com',          country: 'US'       },
    { name: 'Izza Karim',                email: 'ikarim@americloudtelecom.com',            country: 'Pakistan' },
    { name: 'James Faux',                email: 'jfaux@americloudtelecom.com',             country: 'US'       },
    { name: 'Jihad Mounir',              email: 'jmounir@americloudtelecom.com',           country: 'US'       },
    { name: 'John Cooke',                email: 'john.cooke@americloudtelecom.com',        country: 'US'       },
    { name: 'John Gladhill',             email: 'jgladhill@americloudtelecom.com',         country: 'US'       },
    { name: 'Joselito Araneta',          email: 'jaraneta@americloudtelecom.com',          country: 'US'       },
    { name: 'Kamran Khan',               email: 'kakhan@americloudtelecom.com',            country: 'US'       },
    { name: 'Kaushik Gohel',             email: 'kgohel@americloudtelecom.com',            country: 'US'       },
    { name: 'Kiran Dhanalakoti',         email: 'kdhanalakoti@americloudtelecom.com',      country: 'India'    },
    { name: 'Maham Ashraf',              email: 'mashraf@americloudtelecom.com',           country: 'Pakistan' },
    { name: 'Maira Waheed',              email: 'mwaheed@americloudtelecom.com',           country: 'Pakistan' },
    { name: 'Manish Bommakanti',         email: 'mbommakanti@americloudtelecom.com',       country: 'US'       },
    { name: 'Maria Naseer',              email: 'mnaseer@americloudtelecom.com',           country: 'Pakistan' },
    { name: 'Mateen Hussain',            email: 'mhussain@americloudtelecom.com',          country: 'US'       },
    { name: 'Mati ul Haq',               email: 'mhaq@americloudtelecom.com',              country: 'Pakistan' },
    { name: 'Meenakshi Pachauri',        email: 'mpachauri@americloudtelecom.com',         country: 'India'    },
    { name: 'Mohammed Faizan Khan',      email: 'fakhan@americloudtelecom.com',            country: 'US'       },
    { name: 'Mohammed Furquan Ahmed',    email: 'mfahmed@americloudtelecom.com',           country: 'US'       },
    { name: 'Mohammed Hussain',          email: 'mohammed.hussain@americloudtelecom.com',  country: 'US'       },
    { name: 'Mohammed Rayyan Ansari',    email: 'ransari@americloudtelecom.com',           country: 'US'       },
    { name: 'Muhammad Bilal Sheykh',     email: 'msheykh@americloudtelecom.com',           country: 'US'       },
    { name: 'Muhammad Zargham Baig',     email: 'mzbaig@americloudtelecom.com',            country: 'Pakistan' },
    { name: 'Mustafa Mohammed',          email: 'mmohammed@americloud.net',                country: 'US'       },
    { name: 'Naaman Bakshi',             email: 'nbakhshi@americloudtelecom.com',          country: 'US'       },
    { name: 'Nadeem Rasool',             email: 'nrasool@americloudtelecom.com',           country: 'US'       },
    { name: 'Narender Bihan',            email: 'nbihan@americloudtelecom.com',            country: 'US'       },
    { name: 'Nasrulla Ataulla',          email: 'nkhan@americloudtelecom.com',             country: 'US'       },
    { name: 'Nishant Jawale',            email: 'njawale@americloudtelecom.com',           country: 'US'       },
    { name: 'Nitin Nanagiri',            email: 'nnanagiri@americloudtelecom.com',         country: 'US'       },
    { name: 'Nitin Rai',                 email: 'nrai@americloudtelecom.com',              country: 'India'    },
    { name: 'Orlando Medina',            email: 'omedina@americloudtelecom.com',           country: 'US'       },
    { name: 'Pallavi Umar',              email: 'pumar@americloudtelecom.com',             country: 'India'    },
    { name: 'Peter Tijing',              email: 'ptijing@americloudtelecom.com',           country: 'US'       },
    { name: 'Petterson Eden',            email: 'peden@americloudtelecom.com',             country: 'US'       },
    { name: 'Pongthep Kuisangiam',       email: 'pkuisangiam@americloudtelecom.com',       country: 'India'    },
    { name: 'Pushmeena Saeed',           email: 'psaeed@americloudtelecom.com',            country: 'US'       },
    { name: 'Qais Khadher',              email: 'qkhadher@americloudtelecom.com',          country: 'US'       },
    { name: 'Qazi Saud Bin Saeed',       email: 'qsaud@americloudtelecom.com',             country: 'Pakistan' },
    { name: 'Rajesh Bhat',               email: 'rbhat@americloudtelecom.com',             country: 'India'    },
    { name: 'Reem Kirmani',              email: 'rkirmani@americloudtelecom.com',          country: 'Pakistan' },
    { name: 'Rosneidy Galindo',          email: 'rgalindo@americloudtelecom.com',          country: 'US'       },
    { name: 'Sai Manikanta Kolla',       email: 'smkolla@americloudtelecom.com',           country: 'US'       },
    { name: 'Saleem Waheed',             email: 'swaheed@americloudtelecom.com',           country: 'US'       },
    { name: 'Sampa Sarkar',              email: 'ssarkar@americloudtelecom.com',           country: 'India'    },
    { name: 'Sarmad Shahzad',            email: 'sashahzad@americloudtelecom.com',         country: 'Pakistan' },
    { name: 'Sathiamurthy Laxman',       email: 'lsathiamurthi@americloudtelecom.com',    country: 'US'       },
    { name: 'Satyam Kumar Singh',        email: 'ssingh@americloudtelecom.com',            country: 'India'    },
    { name: 'Shafquat Mazhari',          email: 'smazhari@americloudtelecom.com',          country: 'India'    },
    { name: 'Shankar Khan',              email: 'shkhan@americloudtelecom.com',            country: 'India'    },
    { name: 'Smriti Rai',                email: 'smrai@americloudtelecom.com',             country: 'India'    },
    { name: 'Soban Yousaf',              email: 'syousaf@americloudtelecom.com',           country: 'Pakistan' },
    { name: 'Soubhagya Sahoo',           email: 'ssahoo@americloudtelecom.com',            country: 'India'    },
    { name: 'Sri Vishnu Yadala',         email: 'svyadala@americloudtelecom.com',          country: 'US'       },
    { name: 'Syed Muhammad Fateh Kirmani', email: 'fkirmani@americloudtelecom.com',        country: 'Pakistan' },
    { name: 'Tarab Naveed',              email: 'tnaveed@americloudtelecom.com',           country: 'Pakistan' },
    { name: 'Tayyab Ali',                email: 'tali@americloudtelecom.com',              country: 'Pakistan' },
    { name: 'Thirumalesh Naggari',       email: 'tnaggari@americloudtelecom.com',          country: 'US'       },
    { name: 'Vaibhav Phutela',           email: 'vphutela@americloudtelecom.com',          country: 'India'    },
    { name: 'Vikrant Sen Jha',           email: 'vsjha@americloudtelecom.com',             country: 'India'    },
    { name: 'Vineet Kumar Ray',          email: 'vray@americloudtelecom.com',              country: 'India'    },
    { name: 'Yamen Al Zeidi',            email: 'yamenkilani@americloudtelecom.com',       country: 'US'       },
    { name: 'Yashika Sharma',            email: 'ysharma@americloudtelecom.com',           country: 'India'    },
  ],

  // ── Staff roster ──────────────────────────────────────────────────────────
  // role: 'employee' | 'manager' | 'hr'
  // team: managers only — direct reports (email array)
  staff: {

    // ── HR ───────────────────────────────────────────────────────────────────
    'mnaseer@americloudtelecom.com':  { name: 'Maria Naseer',             role: 'hr' },
    'ysharma@americloudtelecom.com':  { name: 'Yashika Sharma',           role: 'hr' },

    // ── EXECUTIVE ────────────────────────────────────────────────────────────
    'swaheed@americloudtelecom.com':  { name: 'Saleem Waheed',            role: 'manager', team: [
      'akhan@americloudtelecom.com',
      'mhussain@americloudtelecom.com',
      'kgohel@americloudtelecom.com',
      'ahsyed@americloudtelecom.com',
      'accounts@americloudtelecom.com',
      'john.cooke@americloudtelecom.com',
      'kdhanalakoti@americloudtelecom.com',
      'peden@americloudtelecom.com',
      'efernandez@americloudtelecom.com',
      'kakhan@americloudtelecom.com',
      'cmpal@americloudtelecom.com',
      'msheykh@americloudtelecom.com',
      'psaeed@americloudtelecom.com',
      'mohammed.hussain@americloudtelecom.com',
      'gadusumalli@americloudtelecom.com',
      'njawale@americloudtelecom.com',
      'yamenkilani@americloudtelecom.com',
      'nbihan@americloudtelecom.com',
    ]},
    'aghani@americloudtelecom.com':   { name: 'Ahmed Ghani',              role: 'manager', team: [
      'akhan@americloudtelecom.com',
      'mhussain@americloudtelecom.com',
      'kgohel@americloudtelecom.com',
      'ahsyed@americloudtelecom.com',
      'accounts@americloudtelecom.com',
      'john.cooke@americloudtelecom.com',
      'kdhanalakoti@americloudtelecom.com',
      'peden@americloudtelecom.com',
      'efernandez@americloudtelecom.com',
      'kakhan@americloudtelecom.com',
      'cmpal@americloudtelecom.com',
      'msheykh@americloudtelecom.com',
      'psaeed@americloudtelecom.com',
      'mohammed.hussain@americloudtelecom.com',
      'gadusumalli@americloudtelecom.com',
      'njawale@americloudtelecom.com',
      'yamenkilani@americloudtelecom.com',
      'nbihan@americloudtelecom.com',
    ]},
    'kgohel@americloudtelecom.com':        { name: 'Kaushik Gohel',       role: 'employee' },
    'john.cooke@americloudtelecom.com':    { name: 'John Cooke',           role: 'employee' },
    'kdhanalakoti@americloudtelecom.com':  { name: 'Kiran Dhanalakoti',    role: 'employee' },
    'gadusumalli@americloudtelecom.com':   { name: 'Gokul Adusumalli',     role: 'employee' },
    'msheykh@americloudtelecom.com':       { name: 'Muhammad Bilal Sheykh',role: 'employee' },
    'psaeed@americloudtelecom.com':        { name: 'Pushmeena Saeed',      role: 'employee' },

    // ── EXECUTIVE / HR ───────────────────────────────────────────────────────
    'ahsyed@americloudtelecom.com':   { name: 'Ahmed Syed',               role: 'manager', team: [
      'mnaseer@americloudtelecom.com',
    ]},

    // ── CONSTRUCTION ─────────────────────────────────────────────────────────
    'njawale@americloudtelecom.com':  { name: 'Nishant Jawale',           role: 'manager', team: [
      'afateh@americloudtelecom.com',
      'nkhan@americloudtelecom.com',
      'nrasool@americloudtelecom.com',
      'aavecilla@americloudtelecom.com',
      'jmounir@americloudtelecom.com',
      'hsharma@americloudtelecom.com',
    ]},
    'afateh@americloudtelecom.com':    { name: 'Abdul Fateh',             role: 'employee' },
    'nkhan@americloudtelecom.com':     { name: 'Nasrulla Ataulla',         role: 'employee' },
    'nrasool@americloudtelecom.com':   { name: 'Nadeem Rasool',            role: 'employee' },
    'aavecilla@americloudtelecom.com': { name: 'Arnell Avecilla',          role: 'employee' },
    'jmounir@americloudtelecom.com':   { name: 'Jihad Mounir',             role: 'employee' },
    'hsharma@americloudtelecom.com':   { name: 'Hirdesh Sharma',           role: 'employee' },

    // ── DESIGN ───────────────────────────────────────────────────────────────
    'nbihan@americloudtelecom.com':       { name: 'Narender Bihan',        role: 'manager', team: [
      'nbakhshi@americloudtelecom.com',
      'hshoaib@americloudtelecom.com',
      'pkuisangiam@americloudtelecom.com',
    ]},
    'nbakhshi@americloudtelecom.com':     { name: 'Naaman Bakshi',         role: 'employee' },
    'hshoaib@americloudtelecom.com':      { name: 'Humzah Shoaib',         role: 'employee' },
    'pkuisangiam@americloudtelecom.com':  { name: 'Pongthep Kuisangiam',   role: 'employee' },

    // ── INTEGRATION ──────────────────────────────────────────────────────────
    'peden@americloudtelecom.com':    { name: 'Petterson Eden',            role: 'manager', team: [
      'apena@americloudtelecom.com',
      'mfahmed@americloudtelecom.com',
      'ransari@americloudtelecom.com',
      'agupta@americloudtelecom.com',
      'anayan@americloudtelecom.com',
      'dprasad@americloudtelecom.com',
      'ssarkar@americloudtelecom.com',
    ]},
    'apena@americloudtelecom.com':    { name: 'Alexis Pena',               role: 'employee' },
    'mfahmed@americloudtelecom.com':  { name: 'Mohammed Furquan Ahmed',    role: 'employee' },
    'ransari@americloudtelecom.com':  { name: 'Mohammed Rayyan Ansari',    role: 'employee' },
    'agupta@americloudtelecom.com':   { name: 'Akshay Gupta',              role: 'employee' },
    'anayan@americloudtelecom.com':   { name: 'Apurv Nayan',               role: 'employee' },
    'dprasad@americloudtelecom.com':  { name: 'Dharmendra Prasad',         role: 'employee' },
    'ssarkar@americloudtelecom.com':  { name: 'Sampa Sarkar',              role: 'employee' },

    // ── COMMISSIONING & INTEGRATION ──────────────────────────────────────────
    'efernandez@americloudtelecom.com': { name: 'Esteban Fernandez',       role: 'manager', team: [
      'afouad@americloudtelecom.com',
      'hshahzad@americloudtelecom.com',
      'tnaveed@americloudtelecom.com',
      'aahsan@americloudtelecom.com',
      'sashahzad@americloudtelecom.com',
      'hbibi@americloudtelecom.com',
      'omedina@americloudtelecom.com',
      'rgalindo@americloudtelecom.com',
      'nbihan@americloudtelecom.com',
      'tali@americloudtelecom.com',
    ]},
    'omedina@americloudtelecom.com':   { name: 'Orlando Medina',           role: 'employee' },
    'rgalindo@americloudtelecom.com':  { name: 'Rosneidy Galindo',         role: 'employee' },
    'afouad@americloudtelecom.com':    { name: 'Ayesha Fouad',             role: 'employee' },
    'hshahzad@americloudtelecom.com':  { name: 'Hamza Shahzad',            role: 'employee' },
    'tnaveed@americloudtelecom.com':   { name: 'Tarab Naveed',             role: 'employee' },
    'aahsan@americloudtelecom.com':    { name: 'Anmol Ahsan',              role: 'employee' },
    'sashahzad@americloudtelecom.com': { name: 'Sarmad Shahzad',           role: 'employee' },
    'hbibi@americloudtelecom.com':     { name: 'Hajira Bibi',              role: 'employee' },
    'tali@americloudtelecom.com':      { name: 'Tayyab Ali',               role: 'employee' },

    // ── OPERATIONS ───────────────────────────────────────────────────────────
    'cmpal@americloudtelecom.com':    { name: 'Chandra Mohan Pal',         role: 'manager', team: [
      'qkhadher@americloudtelecom.com',
      'anwankwo@americloudtelecom.com',
      'pumar@americloudtelecom.com',
      'rbhat@americloudtelecom.com',
      'smazhari@americloudtelecom.com',
      'vphutela@americloudtelecom.com',
      'vsjha@americloudtelecom.com',
      'vray@americloudtelecom.com',
      'amallick@americloudtelecom.com',
      'asharma@americloudtelecom.com',
      'arathaur@americloudtelecom.com',
      'atiwari@americloudtelecom.com',
      'mpachauri@americloudtelecom.com',
      'nrai@americloudtelecom.com',
      'ysharma@americloudtelecom.com',
    ]},
    'qkhadher@americloudtelecom.com':  { name: 'Qais Khadher',             role: 'employee' },
    'anwankwo@americloudtelecom.com':  { name: 'Amaechi Nwankwo',          role: 'employee' },
    'pumar@americloudtelecom.com':     { name: 'Pallavi Umar',              role: 'employee' },
    'rbhat@americloudtelecom.com':     { name: 'Rajesh Bhat',               role: 'employee' },
    'smazhari@americloudtelecom.com':  { name: 'Shafquat Mazhari',          role: 'employee' },
    'vphutela@americloudtelecom.com':  { name: 'Vaibhav Phutela',           role: 'employee' },
    'vsjha@americloudtelecom.com':     { name: 'Vikrant Sen Jha',           role: 'employee' },
    'vray@americloudtelecom.com':      { name: 'Vineet Kumar Ray',          role: 'employee' },
    'amallick@americloudtelecom.com':  { name: 'Asim Mallick',              role: 'employee' },
    'asharma@americloudtelecom.com':   { name: 'Abhay Sharma',              role: 'employee' },
    'arathaur@americloudtelecom.com':  { name: 'Amarjeet Singh Rathore',    role: 'employee' },
    'atiwari@americloudtelecom.com':   { name: 'Anand Tiwari',              role: 'employee' },
    'mpachauri@americloudtelecom.com': { name: 'Meenakshi Pachauri',        role: 'employee' },
    'nrai@americloudtelecom.com':      { name: 'Nitin Rai',                 role: 'employee' },

    // ── MACRO SERVICES ───────────────────────────────────────────────────────
    'mohammed.hussain@americloudtelecom.com': { name: 'Mohammed Hussain',   role: 'manager', team: [
      'jaraneta@americloudtelecom.com',
      'gpolloso@americloudtelecom.com',
      'fnicasio@americloudtelecom.com',
      'dlapada@americloudtelecom.com',
      'mbommakanti@americloudtelecom.com',
      'abautista@americloudtelecom.com',
      'smkolla@americloudtelecom.com',
      'ptijing@americloudtelecom.com',
      'svyadala@americloudtelecom.com',
      'ajkumar@americloudtelecom.com',
      'dpottunuri@americloudtelecom.com',
      'jfaux@americloudtelecom.com',
      'fakhan@americloudtelecom.com',
      'ssingh@americloudtelecom.com',
      'smrai@americloudtelecom.com',
      'mwaheed@americloudtelecom.com',
      'fghulam@americloudtelecom.com',
    ]},
    'jaraneta@americloudtelecom.com':    { name: 'Joselito Araneta',        role: 'employee' },
    'gpolloso@americloudtelecom.com':    { name: 'Gary Polloso',             role: 'employee' },
    'fnicasio@americloudtelecom.com':    { name: 'Ferdinand Nicasio',        role: 'employee' },
    'dlapada@americloudtelecom.com':     { name: 'Daniel Lapada',            role: 'employee' },
    'mbommakanti@americloudtelecom.com': { name: 'Manish Bommakanti',        role: 'employee' },
    'abautista@americloudtelecom.com':   { name: 'Abelino Bautista',         role: 'employee' },
    'smkolla@americloudtelecom.com':     { name: 'Sai Manikanta Kolla',      role: 'employee' },
    'ptijing@americloudtelecom.com':     { name: 'Peter Tijing',             role: 'employee' },
    'svyadala@americloudtelecom.com':    { name: 'Sri Vishnu Yadala',        role: 'employee' },
    'ajkumar@americloudtelecom.com':     { name: 'Ajay Kumar Andapally',     role: 'employee' },
    'dpottunuri@americloudtelecom.com':  { name: 'Dinesh Pottunuri',         role: 'employee' },
    'jfaux@americloudtelecom.com':       { name: 'James Faux',               role: 'employee' },
    'fakhan@americloudtelecom.com':      { name: 'Mohammed Faizan Khan',     role: 'employee' },
    'ssingh@americloudtelecom.com':      { name: 'Satyam Kumar Singh',       role: 'employee' },
    'smrai@americloudtelecom.com':       { name: 'Smriti Rai',               role: 'employee' },
    'mwaheed@americloudtelecom.com':     { name: 'Maira Waheed',             role: 'employee' },
    'fghulam@americloudtelecom.com':     { name: 'Fahad Ghulam',             role: 'employee' },

    // ── SERVICE DELIVERY ─────────────────────────────────────────────────────
    'akhan@americloudtelecom.com':    { name: 'Ammar Khan',                role: 'manager', team: [
      'shkhan@americloudtelecom.com',
      'ssahoo@americloudtelecom.com',
      'mashraf@americloudtelecom.com',
      'marslan@americloudtelecom.com',
      'mzbaig@americloudtelecom.com',
      'qsaud@americloudtelecom.com',
      'bjabeen@americloudtelecom.com',
      'syousaf@americloudtelecom.com',
      'efernandez@americloudtelecom.com',
      'peden@americloudtelecom.com',
      'kakhan@americloudtelecom.com',
      'cmpal@americloudtelecom.com',
      'msheykh@americloudtelecom.com',
      'psaeed@americloudtelecom.com',
    ]},
    'shkhan@americloudtelecom.com':    { name: 'Shankar Khan',              role: 'employee' },
    'ssahoo@americloudtelecom.com':    { name: 'Soubhagya Sahoo',           role: 'employee' },
    'mashraf@americloudtelecom.com':   { name: 'Maham Ashraf',              role: 'employee' },
    'marslan@americloudtelecom.com':   { name: 'Arslan Arif',               role: 'employee' },
    'mzbaig@americloudtelecom.com':    { name: 'Muhammad Zargham Baig',     role: 'employee' },
    'qsaud@americloudtelecom.com':     { name: 'Qazi Saud Bin Saeed',       role: 'employee' },
    'bjabeen@americloudtelecom.com':   { name: 'Bakhtawar Jabeen',          role: 'employee' },
    'syousaf@americloudtelecom.com':   { name: 'Soban Yousaf',              role: 'employee' },

    // ── SALES & GROWTH ───────────────────────────────────────────────────────
    'mhussain@americloudtelecom.com': { name: 'Mateen Hussain',            role: 'manager', team: [
      'fkirmani@americloudtelecom.com',
      'mhaq@americloudtelecom.com',
      'mmohammed@americloud.net',
      'mohammed.hussain@americloudtelecom.com',
      'gadusumalli@americloudtelecom.com',
      'njawale@americloudtelecom.com',
      'yamenkilani@americloudtelecom.com',
      'cmpal@americloudtelecom.com',
      'nbihan@americloudtelecom.com',
    ]},
    'fkirmani@americloudtelecom.com':  { name: 'Syed Muhammad Fateh Kirmani', role: 'employee' },
    'mhaq@americloudtelecom.com':      { name: 'Mati ul Haq',              role: 'employee' },
    'mmohammed@americloud.net':        { name: 'Mustafa Mohammed',         role: 'employee' },

    // ── ACCOUNTING ───────────────────────────────────────────────────────────
    'accounts@americloudtelecom.com': { name: 'Ayesha Syed',              role: 'manager', team: [
      'rkirmani@americloudtelecom.com',
      'ikarim@americloudtelecom.com',
    ]},
    'rkirmani@americloudtelecom.com':  { name: 'Reem Kirmani',             role: 'employee' },
    'ikarim@americloudtelecom.com':    { name: 'Izza Karim',               role: 'employee' },

    // ── TMO ──────────────────────────────────────────────────────────────────
    'kakhan@americloudtelecom.com':    { name: 'Kamran Khan',              role: 'manager', team: [
      'sboopathi@americloudtelecom.com',
    ]},
    'sboopathi@americloudtelecom.com': { name: 'Boopathi Shanmugasundaram', role: 'employee' },

  }

};
